### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by mtmarsh2** [hanjianwei/ACG-Localizer#1]
When I try running 'make' on the ACG main directory, I get this error: 
[ 10%] Building CXX object src/CMakeFiles/acg_localizer.dir/features/visual_words_handler.cc.o
In file included from /home/mike/research/ACG_Localizer_v_1_2_2/src/features/visual_words_handler.cc:25:0:
/home/mike/research/ACG_Localizer_v_1_2_2/src/features/visual_words_handler.hh:48:27: fatal error: flann/flann.hpp: No such file or directory
 #include <flann/flann.hpp>

Do you know why this would be? I ran make on the flann directory and everything compiled correctly so I dont think its that.

**Comment by hanjianwei** [comment]
Do you have flann installed?

I compile this in a Docker container. Dependencies should be required if compelled without Docker. 

You can see what I have done in Dockerfile:  https://github.com/hanjianwei/ACG-Localizer/blob/master/Dockerfile

**Comment by mtmarsh2** [comment]
I think I have flann installed, I can run make from the flann directory and everything compiles, so that means its installed right? I think the issue is maybe with my cmake/FindFLANN.cmake file, maybe I set one of the paths wrong or I dont have one set right? This is also from the directory on the project page, not from this github directory

SET(FLANN_INCLUDE_DIR "/home/mike/research/flann-1.6.11-src")

IF (FLANN_INCLUDE_DIR)
 # Already in cache, be silent
 SET(FLANN_FIND_QUIETLY TRUE)
ENDIF (FLANN_INCLUDE_DIR)

FIND_PATH(FLANN_INCLUDE_DIR flann/flann.hpp
          PATHS "/home/mike/research/flann-1.6.11-src"
                )

set( LIBDIR lib64 )

if( FLANN_INCLUDE_DIR )
   set( FLANN_FOUND TRUE )

   set( FLANN_LIBRARY_DIR "/home/mike/research/flann-1.6.11-src" )

   set( FLANN_LIBRARY optimized flann_cpp debug flann_cpp )

ELSE (FLANN_INCLUDE_DIR)
   SET(FLANN_FOUND FALSE )
ENDIF (FLANN_INCLUDE_DIR )

Also, I tried running your dockerfile, but I got the error:
Sending build context to Docker daemon 
Step 0 : FROM python:0.0.2
Pulling repository python
2014/09/29 12:13:50 Tag 0.0.2 not found in repository python

**Comment by hanjianwei** [comment]
Sorry for the inconvenience!

The Dockerfile is for my own use and python:0.0.2 is my personal image. You can change the first line from

```
FROM python:0.0.2
```

to 

```
FROM ubuntu:14.04
```

**Comment by mtmarsh2** [comment]
Thanks, I got farther but reached another error, is this a problem with linking to the ANN library?

[ 36%] Building CXX object src/CMakeFiles/acg_localizer_active_search.dir/acg_localizer_active_search.cc.o

Linking CXX executable acg_localizer_active_search
CMakeFiles/acg_localizer_active_search.dir/exif_reader/jhead-2.90/jhead.cc.o: In function `DoCommand(char const*, int)':
jhead.cc:(.text+0x461): warning: the use of`mktemp' is dangerous, better use `mkstemp' or`mkdtemp'
CMakeFiles/acg_localizer_active_search.dir/acg_localizer_active_search.cc.o: In function `main':
acg_localizer_active_search.cc:(.text+0x432c): undefined reference to`ANNkd_tree::ANNkd_tree(float**, int, int, int, ANNsplitRule)'
acg_localizer_active_search.cc:(.text+0x43a2): undefined reference to `ANNkd_tree::ANNkd_tree(float**, int, int, int, ANNsplitRule)'
collect2: error: ld returned 1 exit status
make[2]: **\* [src/acg_localizer_active_search] Error 1

**Comment by hanjianwei** [comment]
So weird. Is ANN installed?

**Comment by mtmarsh2** [comment]
Yes it is, I ran the sample tests and they worked in the ANN directory. 

I linked the ANNLibrary and ANNInclude paths in the FindANN.cmake file, and now i get this error. I know the library is compiled, so I think it may have something to do with something else?

[ 36%] Building CXX object src/CMakeFiles/acg_localizer_active_search.dir/acg_localizer_active_search.cc.o
/home/mike/research/ACG-Localizer/src/acg_localizer_active_search.cc: In function ‘int main(int, char**)’:
/home/mike/research/ACG-Localizer/src/acg_localizer_active_search.cc:1091:66: error: cannot convert ‘ANNcoord\* {aka double_}’ to ‘float_’ in assignment
       points_per_component[ cc_id ][ cc_point_counter[ cc_id ] ] = points3D[i];
                                                                  ^
/home/mike/research/ACG-Localizer/src/acg_localizer_active_search.cc:1103:57: error: invalid conversion from ‘float**’ to ‘int’ [-fpermissive]
     kd_trees[i] = new ANNkd_tree( points_per_component[i], nb_points_3D_int, 3 );
                                                         ^
In file included from /home/mike/research/ACG-Localizer/src/acg_localizer_active_search.cc:72:0:
/usr/include/ANN/ANN.h:724:2: error:   initializing argument 1 of ‘ANNkd_tree::ANNkd_tree(int, int, int)’ [-fpermissive]
  ANNkd_tree(       // build skeleton tree
  ^
make[2]: **\* [src/CMakeFiles/acg_localizer_active_search.dir/acg_localizer_active_search.cc.o] Error 1
make[1]: **\* [src/CMakeFiles/acg_localizer_active_search.dir/all] Error 2
make: **\* [all] Error 2

**Comment by mtmarsh2** [comment]
Also, in the 'FindFlann.cmake' file, the comments reference the ANN library, not the FLANN library, is this a error?
- Find FLANN
  Find the native FLANN includes and library
  This module defines
  
  FLANN_INCLUDE_DIR, where to find ANN/ANN.h, etc.
  FLANN_LIBRARIES, the libraries needed to use ANN.
  FLANN_FOUND, If false, do not try to use ANN.
  also defined, but not for general use are
  FLANN_LIBRARY, where to find the ANN library.

**Comment by pangfumin** [comment]
Hi @mtmarsh2,
I meet the same problem. Have you solve it ?

**Comment by zhanlv600** [comment]
I also meet the same problem about ANN. Has anybody solved it like this?

/home/binbin/Documents/code-compile/ACG/ACG-Localizer-master/src/acg_localizer_active_search.cc: In function ‘int main(int, char**)’:
/home/binbin/Documents/code-compile/ACG/ACG-Localizer-master/src/acg_localizer_active_search.cc:1091:66: **error**: cannot convert ‘ANNcoord* {aka double*}’ to ‘float*’ in assignment
       points_per_component[ cc_id ][ cc_point_counter[ cc_id ] ] = points3D[i];
                                                                  ^
/home/binbin/Documents/code-compile/ACG/ACG-Localizer-master/src/acg_localizer_active_search.cc:1103:57: **error**: invalid conversion from ‘float**’ to ‘int’ [-fpermissive]
     kd_trees[i] = new ANNkd_tree( points_per_component[i], nb_points_3D_int, 3 );
                                                         ^
In file included from /home/binbin/Documents/code-compile/ACG/ACG-Localizer-master/src/acg_localizer_active_search.cc:72:0:
/home/binbin/Documents/code-compile/ACG/ann_1.1.2/include/ANN/ANN.h:724:2: **error**:   initializing argument 1 of ‘ANNkd_tree::ANNkd_tree(int, int, int)’ [-fpermissive]
  ANNkd_tree(       // build skeleton tree
  ^
make[2]: *** [src/CMakeFiles/acg_localizer_active_search.dir/acg_localizer_active_search.cc.o] Error 1
make[1]: *** [src/CMakeFiles/acg_localizer_active_search.dir/all] Error 2
make: *** [all] Error 2

**Comment by richaagrawal** [comment]
I end up with the same error: 
/acg_localizer_active_search.cc:1091:66: error: cannot convert ‘ANNcoord* {aka double*}’ to ‘float*’ in assignment
       points_per_component[ cc_id ][ cc_point_counter[ cc_id ] ] = points3D[i];
                                                                  ^
acg_localizer_active_search.cc:1103:57: error: invalid conversion from ‘float**’ to ‘int’ [-fpermissive]
     kd_trees[i] = new ANNkd_tree( points_per_component[i], nb_points_3D_int, 3 );

Any help here?

**Comment by anonymous2792** [comment]
Hi,

anyone got a solution for the above error?

**Comment by uzzybotak** [comment]
I posted the solution on another issue thread

**Comment by eugenelyj** [comment]
I met the same problem and solved it with following steps: 1) replace `typedef double	ANNcoord` with `typedef float	ANNcoord`, 2) make clean ANN project(**important**) 3) build ANN project with `make`

**Comment by alexs7** [comment]
@eugenelyj Hello can you please provide more details on how you fixed it ? Did you make the changes in` acg_localizer_active_search.cc` ?

**Comment by eugenelyj** [comment]
@alexs7 firstly, replace ACCcoord type from `double` to `float` and replace `kmeans_index.h` in ANN project with corresponding file in `acg_localizer/flann_modification`. Then make clean and rebuild ANN project. Finally, if you meet some compiling problem like `cannot convert` you can try `static_cast` or something like that.

**Comment by alexs7** [comment]
@alexs7 By 

> firstly, replace ACCcoord type from double to float

you mean in the file `ann_1.1.2/include/ANN/ANN.h` ?

**Comment by eugenelyj** [comment]
sorry, there is a typo. i mean `ANNcoord`. Yes, it is in `ann_1.1.2/include/ANN/ANN.h`

**Comment by alexs7** [comment]
@eugenelyj I don't know if you came across it but I also had to uncomment line 62 in the `Makefile`, `#cd test ; $(MAKE) $@`. In  `ann_1.1.2/Makefile`

**Comment by eugenelyj** [comment]
i didn't. what error if you don't comment?

**Comment by alexs7** [comment]
@eugenelyj I get an error that some tests would not compile. I dont want to replicate it as I might break it again. It makes sense I think since some tests would expect a double ?

**Comment by pangfumin** [comment]
I provide a runnable docker. 
https://github.com/pangfumin/ACG-localizer

**Comment by alexs7** [comment]
@pangfumin thanks!
